# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a16ef55bb90c08b0ed667dc0b24b29f47d0263210b6f95960305a3bd2f050e54a4f735c923bae67dc67d9208cea810c1e5fd4188e9177b486929fb7f11a42d52

test:
  secret_key_base: 021333fa9f28d09460af8935e5b9474162a654a63fdd0a1ca152df19c39958d31643507a2b74c367bd2c9df782e978770c93433d27a681eaefa8097db4520165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
